### ISSUE TITLE
Improve mobile experience

### ISSUE THREAD

**Issue by landgreen** [landgreen/landgreen.github.io#21]
I'd love help from a professional developer here.

I try to keep the width below 600px.
I'm using this meta tag, but I suspect I could do something better

`<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />`

**Comment by paulmasson** [comment]
This is the tag used in Three.js:

`<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">`

**Comment by landgreen** [comment]
update meta tags


`<meta name="viewport" content="width=device-width, initial-scale=1">`
`<meta name="theme-color" content="#222" />`
`<meta name="description" content="Interactive notes for high school physics.">`

 Add unique description for each page

**Comment by landgreen** [comment]
**Add media rules to:**
get dark header to fill width on zoom / resize (sometimes it leaves a white bar)
for width < 600px shrink LaTex font, scale images, shrink all fonts?
change css grid sizes (not sure how to do this)

check for fixed width elements and switch to `width: 100%`

**Comment by landgreen** [comment]
for full width (600px) canvas elements, resize canvas to be the size of the element they are in
remove `width="600"` from canvas html element
add  `canvas.width = document.getElementsByTagName("article")[0].clientWidth;`
