### ISSUE TITLE
Your physics notes are amazing

### ISSUE THREAD

**Issue by mattcantstop** [landgreen/landgreen.github.io#3]
I found your physics notes on Hacker News. They were amazing. I spent a long time reviewing them and learned a great deal of information. Great work ✨ 

How do you incorporate those notes into your teaching?

**Comment by landgreen** [comment]
Thanks, I project them like a slide show, but I scroll down. If the class gets interested we click on some of the links and use the web site as a starting point for a conversation about the equation/ principle.  The students then do the example problems in class and I randomly pick one to answer. 
https://github.com/landgreen/landgreen.github.io/tree/master/random

Of course, I hope that students use it out of class to study and catch up on what they missed.
