### ISSUE TITLE
Gravity radius fudge factor reduces energy

### ISSUE THREAD

**Issue by rmmh** [landgreen/landgreen.github.io#4]
Adding a [constant factor to radius](https://github.com/landgreen/landgreen.github.io/blob/master/physics/lib/gravityClass.js#L48) introduces error-- which is why the orbits under [Circular Orbits](https://landgreen.github.io/physics/notes/gravity/circular/index.html) don't trace ellipses. 

`const r = Math.max(dx * dx + dy * dy, 1)` would avoid both degenerate zero-radius cases and introducing error.

**Comment by landgreen** [comment]
I wish I had read this a few days ago.  It took me a while to determine this fudge factor was the cause of the precession, but I figured it out a couple days ago.  thanks!
